//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCV.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbCVEntities1 : DbContext
    {
        public DbCVEntities1()
            : base("name=DbCVEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLADMİN> TBLADMİN { get; set; }
        public virtual DbSet<TBLDENEYİMLERİM> TBLDENEYİMLERİM { get; set; }
        public virtual DbSet<TBLEGİTİMLERİM> TBLEGİTİMLERİM { get; set; }
        public virtual DbSet<TBLHAKKIMDA> TBLHAKKIMDA { get; set; }
        public virtual DbSet<TBLHOBİLERİM> TBLHOBİLERİM { get; set; }
        public virtual DbSet<TBLILETISIM> TBLILETISIM { get; set; }
        public virtual DbSet<TBLSERTİFİKALARIM> TBLSERTİFİKALARIM { get; set; }
        public virtual DbSet<TBLSOSYALMEDYA> TBLSOSYALMEDYA { get; set; }
        public virtual DbSet<TBLYETENEKLERIM> TBLYETENEKLERIM { get; set; }
    }
}
